# Use root/12346 as user/password credentials

version: '2'

services:
    alfresco:
        image: gui81/alfresco:latest
        container_name: alfresco
        restart: always
        ports:
            - 58080:8080
        #volumes:
        #    - ./content/:/content/ #:ro  # 配置文件
        #    - ./data/:/alfresco/alf_data/ #:ro # 数据存储
        #environment:
        #    CONTENT_STORE: /content
